#!/bin/zsh
# Create the Play upload key for Brush Buddy.
#
#   ./make-upload-key.sh
#
# Writes upload-keystore.jks and keystore.properties next to this script. Both
# are git-ignored. Run this once, then back both up somewhere you will still
# have them in three years — losing the upload key means going through Google's
# key-reset process before you can ship another update.
#
# This is deliberately a separate, manual step: it mints a long-lived credential
# and only you should decide when that happens.
set -euo pipefail

HERE=${0:A:h}
KEYSTORE=$HERE/upload-keystore.jks
PROPS=$HERE/keystore.properties
ALIAS=upload
JAVA_HOME=${JAVA_HOME:-/Applications/Android Studio.app/Contents/jbr/Contents/Home}
KEYTOOL=$JAVA_HOME/bin/keytool

[[ -x $KEYTOOL ]] || { echo "keytool not found at $KEYTOOL — set JAVA_HOME." >&2; exit 1; }

if [[ -e $KEYSTORE ]]; then
  echo "$KEYSTORE already exists. Refusing to overwrite it — that would make"  >&2
  echo "every already-published update unshippable. Delete it by hand if you"  >&2
  echo "are certain it was never used."                                         >&2
  exit 1
fi

echo "Distinguished name for the certificate (shown to nobody, but permanent)."
read "CN?  Your name or company [Marijn Vandevoorde]: "
CN=${CN:-Marijn Vandevoorde}
read "C?  Two-letter country code [BE]: "
C=${C:-BE}

# 40 hex characters (160 bits) from the system RNG: strong, and nothing to
# memorise since it is stored in keystore.properties right next to the keystore.
#
# Not `tr -dc … </dev/urandom | head -c 40`: `head` closes the pipe as soon as it
# has 40 bytes, `tr` dies of SIGPIPE, and under `set -o pipefail` that aborts the
# whole script (exit 141) before a key is ever written.
PASSWORD=$(openssl rand -hex 20)

"$KEYTOOL" -genkeypair \
  -keystore "$KEYSTORE" \
  -alias "$ALIAS" \
  -keyalg RSA -keysize 4096 \
  -validity 10000 \
  -storepass "$PASSWORD" -keypass "$PASSWORD" \
  -dname "CN=$CN, O=$CN, C=$C"

cat > "$PROPS" <<EOF
# Generated by make-upload-key.sh — git-ignored. Back this up together with
# upload-keystore.jks; the password exists nowhere else.
storeFile=upload-keystore.jks
storePassword=$PASSWORD
keyAlias=$ALIAS
keyPassword=$PASSWORD
EOF
chmod 600 "$PROPS" "$KEYSTORE"

echo
echo "Created:"
echo "  $KEYSTORE"
echo "  $PROPS"
echo
echo "SHA-256 fingerprint (Play Console shows this once the first upload lands):"
"$KEYTOOL" -list -v -keystore "$KEYSTORE" -alias "$ALIAS" -storepass "$PASSWORD" \
  | grep -i "SHA256:" || true
echo
echo "⚠️  Back up BOTH files now. Without them you cannot publish updates."
